language: csharp
os:
  - linux
  - osx
mono:
  - latest
script:
  - ./build.sh --target "Travis" --platform "Mono" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/190345f2f4350d168c39
    on_success: change
    on_failure: always
    on_start: never
cache:
  directories:
    - packages
    - tools
