language: csharp
os:
  - linux
  - osx
dist: trusty
mono:
  - latest
dotnet: 1.0.1
script:
  - ./build.sh --target "Travis" --platform "Mono" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/190345f2f4350d168c39
    on_success: change
    on_failure: always
    on_start: never
