version: 2
jobs:
  build:
    working_directory: ~/ReactiveHistory
    docker:
      - image: microsoft/dotnet:2.1.401-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore src/ReactiveHistory
      - run: dotnet build src/ReactiveHistory/ReactiveHistory.csproj -c Release -f netstandard2.1
      - run: dotnet restore tests/ReactiveHistory.UnitTests
      - run: dotnet test tests/ReactiveHistory.UnitTests/ReactiveHistory.UnitTests.csproj -c Release -f netcoreapp2.1
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/4ca4750799464a669fb4
