version: 2
jobs:
  build:
    working_directory: ~/ReactiveHistory
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore src/ReactiveHistory
      - run: dotnet build src/ReactiveHistory/ReactiveHistory.csproj
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/4ca4750799464a669fb4
